version: 2
jobs:
  build:
    working_directory: ~/electron-redux
    docker:
      - image: node:7.6.0
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: mkdir ~/electron-redux/artifacts
      - restore_cache:
          key: electron-redux-{{ .Branch }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: electron-redux-{{ .Branch }}
          paths:
            - "~/.cache/yarn"
            - "~/electron-redux/node_modules"
      - run:
          name: Run Tests
          command: yarn test
